### ISSUE TITLE
Add the OSMAnd .obf file format to the Export Tool

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/hotosm-project-ideas#18]
**Proposed by:** Mhairi O'Hara     

**Summary:** Currently other services are relied on to update OSMAnd during activations. Allowing users to update this themselves through the [HOT Exports Tool](http://export.hotosm.org/en) would help make activations more effective. 

**Skills Required:** Ruby on Rails, Perl, Shell, SQLite, PostgreSQL, HTML5, CSS

**Possible Mentors:** ???

**Notes:** This project proposal is taken from the [hot-exports](https://github.com/hotosm/hot-exports), where it is listed as issue [#77](https://github.com/hotosm/hot-exports/issues/77).

**Comment by cgiovando** [comment]
@dodobas can you estimate the time and skills required for this project? @mataharimhairi we should make sure these project ideas are worth three months of coding if we tag them for GSoC.  

Any developer from the project that we can ask about mentoring?

**Comment by bgirardot** [comment]
I haven't had a chance to look at these hot export server ideas yet, but one thing to keep in mind is that the software runs on geofabrik hardware somewhere. I have tried to get it installed on my local machine but never had any luck, but I am not a Ruby on Rails developer.

**Comment by mataharimhairi** [comment]
@cgiovando Yes, I totally agree. We will have to see if this job is realistic for a 3 month internship, otherwise it can't be used as a project proposal. I thought I would add it as an issue (project idea) first, so that we might get some feed back on it, which hopefully Dražen can help us with!

**Comment by dodobas** [comment]
This should be merged with #17

**Comment by mataharimhairi** [comment]
I have merged this project idea with issue #17.
