### ISSUE TITLE
Usability Testing for the HOT Tasking Manager User Interface (UI)

### ISSUE THREAD

**Issue by cgiovando** [hotosm/hotosm-project-ideas#2]
**Proposed by:** Mhairi O'Hara

**Summary:** Enhancements are currently being made to the Tasking Manager interface. Once these changes are made, usability testing will be required to determine how easy it is to use the online tool based on the sites flow, navigation, layout, speed and content.

Major points to keep in mind when testing usability:
- Learnability: How easy is it for users to accomplish basic tasks the first time they encounter the design?
- Efficiency: How fast can experienced users accomplish tasks?
- Memorability: When users return to the design after a period of not using it, does the user remember enough to use it effectively the next time, or does the user have to start over again learning everything?
- Errors: How many errors do users make, how severe are these errors and how easily can they recover from the errors?
- Satisfaction: How much does the user like using the system?

**Skills Required:** Attention to detail, good communication skills, ability to engage with open source community, empirical analysis, knowledge of UI designs 

**Possible Mentors:**   Mhairi O'Hara (@mataharimhairi)

**Notes:**  Usability testing will probably be conducted through a number of methods, including user feedback, mining statistics from the Tasking Manager, and a series of testing.

**Comment by mataharimhairi** [comment]
@pgiraud Hey Pierre, I don't think I've introduced myself yet, so sorry to jump right in and ask if you could possibly mentor this project? I think you would be ideal as you are heavily involved with upgrading the TM for the version 2.0 release.

And if I am correct, you were also Nikita Agarwal mentor on the last FOSS Outreach Program for Women, which focused on improving the TM homepage and this project follows on from that.

Please let me know if this is something you are would like to take on!

**Comment by rekth** [comment]
Hello,

I am interested in contributing to this project through Outreachy. With who can I talk to to prepare myself for the application and learn a bit more about the project and what to expect?
Some suggestions of improving the learning process have already come to mind. Is the best process to submit them here directly?

Thanks,
rekth

**Comment by lumneh** [comment]
Hi,
I am a computer engineering student and am interested in contributing to this project through the outcheachy program 2015. Please could someone help me on how to get started.
Thanks

**Comment by lumneh** [comment]
Hello,
I sent a message earlier stated my interest in contributing to this project for Outreachy 2015, but I haven't had a reply. Could someone please tell me how to get started?

Thanks
Angela.

**Comment by mataharimhairi** [comment]
Hello Angela and Rekth,

Sorry for the slow reply, and thank you for your interest. To start with, I would recommend that you both familiarise yourselves with the Tasking Manager [1]. If you haven't already done so, please review the general requirements of the Outreachy internship [2] and keep in mind that a minimum of 40 hrs a week must be dedicated to the program, carried out remotely from the 25th May until 25th August.

[1] http://tasks.hotosm.org/
[2] https://www.gnome.org/outreachy/

The next step in the application process would be to complete the items listed below and send them to apply-outreachy@hotosm.org:
- A short paragraph explaining why you are applying and what involvement, if you have had any, in open source projects.
- A simple resume showing previous activities and experience. And please feel free to include work that are not necessarily open source related.
- A draft outlining a proposed time schedule of your availability for the project, incorporating the expected 40 hrs per week from the 25th May to the 25th August.
- The completed Tasking Manager UI Usability Testing [task](https://github.com/hotosm/HOT-Project-Ideas/wiki/OSM-Tasking-Manager-UI-Usability-Testing) as your contribution to the project.

**Comment by lumneh** [comment]
Thanks very much @mataharimhairi, am immediately going to start  familiarising myself as you proposed above.

**Comment by rekth** [comment]
Hi @mataharimhairi 
If there is some spare time, a bit more information about this project and what to expect from participating in the internship would be much appreciated.
Maybe also some details on what is expected from us to successfully complete the internship. For example, I understand that the deliverables is what's required but the description entails that a variety of methods can be used for gathering user preferences.
Would it be possible to discuss this on irc maybe?

**Comment by mataharimhairi** [comment]
Hello Rekth, 

Yes, let's set a time to meet on IRC so we can discuss this further. I've sent you an e-mail with some time options.

Kind regards, 

Mhairi

**Comment by mataharimhairi** [comment]
@lumneh I just wanted to let you know that I had an IRC chat with Rekth after we arranged a time together. This would be the best way to catch me online, as I am not always available. Would you like to have a chat sometime?

I am also happy to look over the application briefly - well really just the task part of the application before you submit it. So please do not hesitate to get in touch with me regarding this.

**Comment by mataharimhairi** [comment]
Dear applicants, @rekth, @lumneh 

Please do not forget to submit your interest for the project via the Outreachy website:

https://outreachy.gnome.org

You must submit your proposal by 24th March 2015 19:00UTC. When submitting your application make sure you select "OpenStreetMap" from the organisation list.

Futher edits and changes to your application can still be made after this, but it is vital that this initial deadline is not missed.

**Comment by lumneh** [comment]
Hey @mataharimhairi, 
I would be very much delighted to have a chat with you on the IRC channel, please just let me know the time and day when you are available.\

Thanks

**Comment by mataharimhairi** [comment]
@lumneh I would be more than happy to chat to you today or tomorrow. Please send me an e-mail (mhairi.ohara@hotosm.org) so we can arrange a suitable time based on our locations.

**Comment by jsritchie** [comment]
Hello, 

My name is Jacinta Ritchie, and I learned about Outreachy this sunday at LibrePlanet conference at MIT. I was attending to represent Vermont Law School's Center for Legal Innovation. Brian Mako Hill plugged the program and after some investigation OSM seems to be the best fit! 

I'm finishing up my law degree at Vermont, specializing in Energy Law and Regulation. My goal is to make this technology accessible to tribes and various stakeholders to map cultural resources to improve energy resource management optimization tools.  In any case, you are doing amazing work and I hope to contribute anyway I can. 

I am interested in the documentation, and curriculum development projects as well. Should I submit different contributions and/or show interest in the other forums? I know the deadline is fast approaching, so best of luck in the review! 

Thank you, 

Jacinta

**Comment by mataharimhairi** [comment]
Hello @jsritchie, @jpinkidu,  

Please be aware that the application must be submitted via the Outreachy website by today 24th March 2015 19:00 UTC. When submitting your application make sure you select "OpenStreetMap" from the organisation list:

https://outreachy.gnome.org

Futher edits and changes to your application can still be made after this, but it is vital that this initial deadline is not missed. Please complete the items below and add them to your application:
- A short paragraph explaining why you are applying and what involvement, if you have had any, in open source projects.
- A simple resume showing previous activities and experience. And please feel free to include work that are not necessarily open source related.
- A draft outlining a proposed time schedule of your availability for the project, incorporating the expected 40 hrs per week from the 25th May to the 25th August.
- The completed Tasking Manager UI Usability Testing [task](https://github.com/hotosm/HOT-Project-Ideas/wiki/OSM-Tasking-Manager-UI-Usability-Testing) as your contribution to the project.

**Comment by jpinkidu** [comment]
Hi,
my name is Julia. I just learned about the Outreachy Program.
I'm interested in contributing to this project and I hope it is not too late to reach out for it. I already  took a look at the Tasking Manager. Have you any other suggestions besides the ones you mentioned before?

Thanks a lot!
Julia

**Comment by mataharimhairi** [comment]
@jpinkidu I think at this very late notice, it is best you stick to one proposal. If you are interested in this project, please follow the steps in the comment above your previous comment. Good luck!
