### ISSUE TITLE
Promote OpenAerialMap to other Communities

### ISSUE THREAD

**Issue by cgiovando** [hotosm/hotosm-project-ideas#3]
**Proposed by:** Cristiano Giovando (@cgiovando)  
**Summary:** OpenAerialMap is an open source platform offering a simple way to host and provide access to aerial imagery. Its purpose within HOT is to facilitate sharing of aerial imagery after a disaster for humanitarian response mapping. The goal of this project is to promote OAM to other communities of potential users outside of HOT. This will be done by creating informational material, making presentations, demonstrating use case examples, introducing the project on public fora, mailing lists and social media. The selected intern should be familiar with open source technology, mapping and aerial imaging.  
**Skills Required:** excellent writing, demonstrated ability to engage through social media, interest in drone/UAV technology, knowledge of remote sensing principles  
**Possible Mentors:** Cristiano Giovando (@cgiovando)  
**Notes:** more details at https://github.com/hotosm/OpenAerialMap

**Comment by SonaliAg** [comment]
Hi,
I am interested in this project and want to apply for it through Outreachy. Can you pls guide me from where to start contributing in it. I am familiar with remote sensing.

**Comment by sandraemma03** [comment]
Hello my name is Sandra-Emma. Am a 3rd year software engineering student at the university of Buea Cameroon. I am apply for Outreachy under the OSM organisation and am interested in the project on Promote OpenAerialMap to other Communities. I dont know if i could have a guide on where to start first. Thanks

**Comment by Abhilasha23singh** [comment]
Hello,

I am Abhilasha from IIT BHU, India. I am interested in contributing to this project through Outreachy 2015. Who can I get I touch with to learn more about the project and to submit my proposal ?

Thanks and Regards,
Abhilasha Singh

**Comment by Abhilasha23singh** [comment]
Hello,

I am Abhilasha from IIT BHU, India. I am interested in contributing to this project through Outreachy 2015. Who can I get I touch with to learn more about the project and to submit my proposal ?

Thanks and Regards,
Abhilasha Singh

**Comment by cgiovando** [comment]
Hello @SonaliAg @sandraemma03 and @Abhilasha23singh  
Thanks for your interest in this project. In order to get started please get familiar with OpenAerialMap by visiting https://github.com/hotosm/OpenAerialMap  

Before applying for this project idea through the Outreachy program, please provide two examples of communities or organizations that would benefit from the OpenAerialMap project. Describe what features of OAM would address functional needs in current workflows or specific use case scenarios.

Send your examples along with a short motivation statement of why you are interested in OAM to cristiano.giovando@hotosm.org

**Comment by cgiovando** [comment]
@SonaliAg @sandraemma03 @Abhilasha23singh and anyone else interested in applying to this project under the Outreachy program, please submit your proposal by 24th March 2015 19:00UTC. When submitting your application make sure you select "OpenStreetMap" from the organization list.

For more details and to apply, visit https://outreachy.gnome.org
