### ISSUE TITLE
Improve LearnOSM documentation (content, site, structure)

### ISSUE THREAD

**Issue by cgiovando** [hotosm/hotosm-project-ideas#4]
**Proposed by:** Althio  
**Summary:**  
**Skills Required:**  depending on actual project, web design, GitHub/Jekyll or similar, computer-aided translation [CAT], documentation writing.  
**Possible Mentors:** someone in the LearnOSM team?  
**Notes:**  Some suggestions:
- Review implementation / internal structure with Jekyll
- Jekyll plugins (Table of contents, navigation, glossary, epub/pdf…)
- Structure of content (guides, sections)
- Translation issues (workflow in general, using non-technical tools, Translation memory "shared glossary" with other projects…)
- Guidelines for images (workflow, size, naming, folders…)

**Comment by althio** [comment]
These suggestions are now detailed as separate project ideas in #10 #11 #12 #13 #14.

**Comment by cgiovando** [comment]
Great, thanks Althio! I'm going to close this one then.
