### ISSUE TITLE
Develop a QGIS plugin for OpenAerialMap

### ISSUE THREAD

**Issue by cgiovando** [hotosm/hotosm-project-ideas#6]
**Proposed by:** Cristiano Giovando (@cgiovando)  
**Summary:** the goal of this project is to create a QGIS plugin with a graphic user interface to tile local aerial imagery dataset and upload them to OAM. The development will implement the OAM upload API commands for sending ready-tiles to the main OAM server or a specific node. The QGIS plugin could also consume OAM-C API and facilitate search/browse/get imagery for an area, or download unprocessed imagery data, basically a desktop tool for OAM.  
**Skills Required:** Python, QT  
**Possible Mentors:** Dražen Odobašić,  Cristiano Giovando  
**Notes:**

**Comment by heatherleson** [comment]
Hey I would provide the links to each of the software and HOT projects in this ticket. There are QGIS experts in the HOT community. Maybe send a note to the list about the exact needs?

**Comment by dodobas** [comment]
Willing to mentor,

QGIS plugin could also consume OAM-C API and facilitate search/browse/get imagery for an area, or download unprocessed imagery data ... basically a desktop tool for OAM

**Comment by tassia** [comment]
Hello,
May I still apply for this project?
I see that it was removed from the Outreachy 2015 page, but if dodobas is still willing to mentor, I would probably apply to this one.
Thanks!

**Comment by cgiovando** [comment]
Hi @tassia thanks for your interest in this project idea. It was unlisted only because it did not receive much attention and the OAM project is still in its early phase. I'm happy to repost it if you feel like it would be a good match for your skills and interests. @dodobas myself and probably someone else from QGIS-Devs would be excited and happy to mentor.

To start, we would like to know about your experience with Python and GIS in general. Since the OpenAerialMap project is just starting development (but it will have a working release by the time of the internship), I suggest you would do a demonstration of "code contribution" by creating a sample QGIS plugin. This can be a simple tool that takes any raster layer loaded in the map canvas and allows the user to upload it to a Web service (SFTP, AWS S3, REST APIs, etc) through a basic GUI. Here are some direction for creating plugins:

http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/plugins.html

As I said It could be as simple as a plugin window that calls the current loaded layer, a drop-down list for target destinations, then an "upload" button that executes the upload sequence (SFTP or REST API). 

Let me know if that's something you could do by next week, we are here to answer any question you may have.

**Comment by tassia** [comment]
Hi cgiovando,
This all sounds great!
So I'll start coding asap and when I have doubts or something to show I'll get in touch.
Thanks!
Tassia.

**Comment by cgiovando** [comment]
@tassia and anyone else interested in applying to this project under the Outreachy program, please submit your proposal by 24th March 2015 19:00UTC. When submitting your application make sure you select "OpenStreetMap" from the organization list.

For more details and to apply, visit https://outreachy.gnome.org
